@startuml

title __TO-DO TASKS TRACKER APP CLASS DIAGRAM__\n

  namespace ph.dlsu.cpei.project {
    abstract class ph.dlsu.cpei.project.Category {
        {abstract} + addHigh()
        {abstract} + addLow()
        {abstract} + addMed()
    }
  }
  

  namespace ph.dlsu.cpei.project {
    class ph.dlsu.cpei.project.Education {
        + addHigh()
        + addLow()
        + addMed()
    }
  }
  

  namespace ph.dlsu.cpei.project {
    class ph.dlsu.cpei.project.Games {
        + addHigh()
        + addLow()
        + addMed()
    }
  }
  

  namespace ph.dlsu.cpei.project {
    class ph.dlsu.cpei.project.Home {
        + addHigh()
        + addLow()
        + addMed()
    }
  }
  

  namespace ph.dlsu.cpei.project {
    class ph.dlsu.cpei.project.Meeting {
        + addHigh()
        + addLow()
        + addMed()
    }
  }
  

  namespace ph.dlsu.cpei.project {
    class ph.dlsu.cpei.project.TaskApp {
        - fileNameNumber : int
        {static} + main()
        + run()
        - menuDisplay1()
        - menuDisplay2()
        - menuDisplay3()
        - menuDisplay4()
        - menuDisplay5()
    }
  }
  

  namespace ph.dlsu.cpei.project {
    class ph.dlsu.cpei.project.Update {
        - dates : Date[]
        - days : long[]
        - hours : long[]
        - minutes : long[]
        - seconds : long[]
        - taskName : String[]
        - time : long[]
        - years : long[]
        + category()
        + category()
        + category()
        + category()
        + getDates()
        + getDays()
        + getHours()
        + getMinutes()
        + getSeconds()
        + getTaskName()
        + getYears()
        + priority()
        + priority()
        + priority()
        + remove()
        + timeAndDate()
        + timePriority()
        + timePriority()
        + timePriority()
    }
  }
  

  namespace ph.dlsu.cpei.project {
    class ph.dlsu.cpei.project.UserDatabase {
        - counter : int
        - fileName : String
        - limit : int
        - newCount : String
        - oldCount : String
        + create()
        + login()
        + success()
    }
  }
  

  ph.dlsu.cpei.project.Education -up-|> ph.dlsu.cpei.project.Category
  ph.dlsu.cpei.project.Games -up-|> ph.dlsu.cpei.project.Category
  ph.dlsu.cpei.project.Home -up-|> ph.dlsu.cpei.project.Category
  ph.dlsu.cpei.project.Meeting -up-|> ph.dlsu.cpei.project.Category
  ph.dlsu.cpei.project.TaskApp -up-|> acm.program.ConsoleProgram
  ph.dlsu.cpei.project.TaskApp o-- ph.dlsu.cpei.project.Update : sort


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
